### FILE EXTENSIONS ###
NUMPY_ARRAY_EXTENSION = "npy"
DICOM_FILE_EXTENSION = "dcm"
JSON_FILE_EXTENSTION = "json"
TXT_FILE_EXTENSION = "txt"
GZ_FILE_EXTENSION = "gz"
MHA_FILE_EXTENSION = "mha"
NRRD_FILE_EXTENSION = "nrrd"
NIFTI_FILE_EXTENSION = "nii"
CONFIG_FILE_EXTENSION = "cfg"
PKL_FILE_EXTENSION = "pkl"
BDF_FILE_EXTENSION = "bdf"

### NUMERIC CONSTANTS ###
EPS = 1e-10
